# Generated by Django 5.1 on 2024-08-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=225, verbose_name='زیرعنوان')),
                ('description', models.TextField(verbose_name='توضیح ')),
            ],
            options={
                'verbose_name': 'هدر ',
                'verbose_name_plural': 'هدر ویلاگ',
            },
        ),
    ]
