# Generated by Django 5.1 on 2024-08-19 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=255, verbose_name='زیر عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'تیم',
                'verbose_name_plural': 'تیمها',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Team', verbose_name='تصویر')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('role', models.CharField(max_length=255, verbose_name='پوزیشن')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='TeamApp.team')),
            ],
            options={
                'verbose_name': 'آیتم',
                'verbose_name_plural': 'آیتم ها',
            },
        ),
    ]
