# Generated by Django 5.1 on 2024-08-19 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=255, verbose_name='زیر عنوان')),
                ('text1', models.TextField(verbose_name='متن اول')),
                ('text2', models.TextField(verbose_name='متن دوم')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('subtitle', models.CharField(max_length=255, verbose_name='زیر عنوان')),
                ('description', models.TextField(verbose_name='متن ')),
            ],
            options={
                'verbose_name': 'جایزه',
                'verbose_name_plural': 'جایزه ها',
            },
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='عنوان')),
                ('value', models.PositiveSmallIntegerField(default=0, verbose_name='مقدار')),
            ],
            options={
                'verbose_name': 'شمارنده',
                'verbose_name_plural': 'شمارنده ها',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='About', verbose_name='نگاره')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='AboutApp.about')),
            ],
            options={
                'verbose_name': 'عکس',
                'verbose_name_plural': 'گالری',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('year', models.CharField(max_length=5, verbose_name='سال')),
                ('subtitle', models.CharField(max_length=255, verbose_name='زیر عنوان')),
                ('text1', models.TextField(verbose_name='متن ')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='AboutApp.award')),
            ],
        ),
    ]
