# Generated by Django 5.1 on 2024-08-19 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('subtitle', models.CharField(max_length=255, verbose_name='زیر عنوان')),
                ('description', models.TextField(verbose_name='زیرنوشت')),
                ('front_img', models.ImageField(blank=True, null=True, upload_to='Home', verbose_name='عکس')),
                ('back_img', models.ImageField(blank=True, null=True, upload_to='Home', verbose_name='عکس پس زمینه')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما 1',
            },
        ),
        migrations.CreateModel(
            name='AboutTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('subtitle', models.CharField(max_length=255, verbose_name='زیر عنوان')),
                ('description', models.TextField(verbose_name='زیرنوشت')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Home', verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما 2',
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_img', models.ImageField(blank=True, null=True, upload_to='Home', verbose_name='عکس پس زمینه')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('subtitle', models.CharField(max_length=255, verbose_name='زیر عنوان')),
                ('description', models.TextField(verbose_name='زیرنوشت')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Home', verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'هدر سایت',
                'verbose_name_plural': 'هدر سایت',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام شرکت')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Home', verbose_name='لوگو')),
            ],
            options={
                'verbose_name': 'همکار',
                'verbose_name_plural': 'همکاران',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('subtitle', models.TextField(verbose_name='زیرنوشت')),
            ],
            options={
                'verbose_name': 'مشتریان',
                'verbose_name_plural': 'مشتریان',
            },
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='لیبل')),
                ('value', models.CharField(max_length=255, verbose_name='مقدار')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter', to='HomeApp.abouttwo')),
            ],
            options={
                'verbose_name': 'شمارنده',
                'verbose_name_plural': 'شمارنده ها',
            },
        ),
        migrations.CreateModel(
            name='TestItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('role', models.CharField(max_length=255, verbose_name='شغل')),
                ('text', models.TextField(verbose_name='زیرنوشت')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Home', verbose_name='تصویر')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tetsItems', to='HomeApp.testimonial')),
            ],
            options={
                'verbose_name': 'آیتم',
                'verbose_name_plural': 'آیتمها',
            },
        ),
    ]
